# - Try to find GLEW
# Once done this will define
#
#  GLEW_FOUND - system has GLEW
#  GLEW_INCLUDE_DIRS - the GLEW include directories
#  GLEW_LIBRARIES - Link these to use GLEW
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GLEW_INCLUDE_DIR NAMES GL/glew.h)
FIND_LIBRARY(GLEW_LIBRARY NAMES GLEW glew32)

SET(GLEW_LIBRARIES ${GLEW_LIBRARY})
SET(GLEW_INCLUDE_DIRS ${GLEW_INCLUDE_DIR})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG GLEW_LIBRARY GLEW_INCLUDE_DIR)

MARK_AS_ADVANCED(GLEW_INCLUDE_DIR GLEW_LIBRARY)