# - Try to find squish
# Once done this will define
#
#  SQUISH_FOUND - system has squish
#  SQUISH_INCLUDE_DIRS - the squish include directories
#  SQUISH_LIBRARIES - link these to use squish
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(SQUISH_INCLUDE_DIR NAMES squish.h)
FIND_LIBRARY(SQUISH_LIBRARY NAMES squish)

SET(SQUISH_LIBRARIES ${SQUISH_LIBRARY})
SET(SQUISH_INCLUDE_DIRS ${SQUISH_INCLUDE_DIR})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SQUISH DEFAULT_MSG SQUISH_LIBRARY SQUISH_INCLUDE_DIR)

MARK_AS_ADVANCED(SQUISH_INCLUDE_DIR SQUISH_LIBRARY)
