# - Try to find squish
# Once done this will define 
# 
#  SQUISH_FOUND - system has squish
#  SQUISH_INCLUDE_DIR - the squish include directory 
#  SQUISH_LIBRARIES - Link these to use squish
# 

FIND_PATH(SQUISH_INCLUDE_DIR NAMES squish.h
  PATHS
  ENV CPATH
  /usr/include
  /usr/local/include
  NO_DEFAULT_PATH
)
FIND_PATH(SQUISH_INCLUDE_DIR NAMES squish.h)

FIND_LIBRARY(SQUISH_LIBRARIES NAMES squish
  PATHS
  ENV LD_LIBRARY_PATH
  ENV LIBRARY_PATH
  /usr/lib64
  /usr/lib
  /usr/local/lib64
  /usr/local/lib
  NO_DEFAULT_PATH
)
FIND_LIBRARY(SQUISH_LIBRARIES NAMES squish)

IF(SQUISH_INCLUDE_DIR AND SQUISH_LIBRARIES)
   SET(SQUISH_FOUND TRUE)
ENDIF(SQUISH_INCLUDE_DIR AND SQUISH_LIBRARIES)

IF(SQUISH_FOUND)
  IF(NOT SQUISH_FIND_QUIETLY)
    MESSAGE(STATUS "Found squish: ${SQUISH_LIBRARIES}")
  ENDIF(NOT SQUISH_FIND_QUIETLY)
ELSE(SQUISH_FOUND)
  IF(SQUISH_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find squish")
  ENDIF(SQUISH_FIND_REQUIRED)
ENDIF(SQUISH_FOUND)

MARK_AS_ADVANCED(SQUISH_INCLUDE_DIR SQUISH_LIBRARIES )
