# - Try to find Libintl
# Once done this will define 
#
#  LIBINTL_FOUND - system has Libintl
#  LIBINTL_INCLUDE_DIRS - the Libintl include directories
#  LIBINTL_LIBRARIES - link these to use Libintl
#

INCLUDE(CheckFunctionExists)
INCLUDE(FindPackageHandleStandardArgs)
  
FIND_PATH(LIBINTL_INCLUDE_DIR libintl.h)
 
IF(LIBINTL_INCLUDE_DIR)
  CHECK_FUNCTION_EXISTS(dgettext LIBINTL_LIBC_HAS_DGETTEXT)
 
  SET(LIBINTL_LIB_FOUND FALSE)
  IF(LIBINTL_LIBC_HAS_DGETTEXT)
    SET(LIBINTL_LIBRARY)
    SET(LIBINTL_LIB_FOUND TRUE)
  ELSE(LIBINTL_LIBC_HAS_DGETTEXT)
    FIND_LIBRARY(LIBINTL_LIBRARY NAMES intl)
    IF(LIBINTL_LIBRARY)
      SET(LIBINTL_LIB_FOUND TRUE)
    ENDIF(LIBINTL_LIBRARY)
  ENDIF(LIBINTL_LIBC_HAS_DGETTEXT)
ENDIF(LIBINTL_INCLUDE_DIR)

SET(LIBINTL_LIBRARIES ${LIBINTL_LIBRARY})
SET(LIBINTL_INCLUDE_DIRS ${LIBINTL_INCLUDE_DIR})
 
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Libintl DEFAULT_MSG LIBINTL_INCLUDE_DIRS LIBINTL_LIB_FOUND)
 
MARK_AS_ADVANCED(LIBINTL_INCLUDE_DIR LIBINTL_LIBRARY LIBINTL_LIBC_HAS_DGETTEXT LIBINTL_LIB_FOUND)